[package]
name = "rust_practice"
version = "0.1.0"
author = "Ashish Sharma"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.8.5"
colored = "2.0.0"
unicode-segmentation = "1.7.1"